### ISSUE TITLE
User friendly redesign tracking issue

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#3]
- [x] general ui
	- [x] toast
	- [x] modal
	- [x] confirm dialog

- [x] Waitlist
	- [x] You can sign up for the waitlist
	- [x] You can be "approved" and see the actual wallet
	- [x] Fix the flash on load
	- [x] actually check with the backend for approval

- [x] Integration
	- [x] Pull in node manager package and put it into a "context" object
	- [x] Pick a better solution that react-query for doing async calls to node manager

~~- [ ] Setup~~
	~~- [ ] a welcome screen prompting them to write down their seed~~
	Setup moved to: https://github.com/MutinyWallet/mutiny-web/issues/30
- [x] Home screen
	- [x] show balance
	- [x] balance polling
	- [x] list activity
		- [x] sends
		- [x] receives (make sure to hide ones that we gave up on)

- [x] Send
	- [x] scan qr codes
	- [x] paste stuff
	~~- [ ] "WAILA" (what am I looking at... take the string and figure out what it is)~~ https://github.com/MutinyWallet/mutiny-web/issues/31
	- [x] send lightning
	- [x] send on-chain
	~~- [ ] send lnurl / lightning address~~ https://github.com/MutinyWallet/mutiny-web/issues/31
	- [x] add amounts when relevant
	- [x] add memo
	~~- [ ] confirm~~ https://github.com/MutinyWallet/mutiny-web/issues/32
	- [x] success
	~~- [ ] fail~~ https://github.com/MutinyWallet/mutiny-web/issues/32

- [x] Receive
	- [x] create lightning invoice
	- [x] use lsp method for lightning invoice
	- [x] create on-chain address (or should we do lightning receives only for now?)
	- [x] display QR code
	- [x] unified
	- [x] success screen

~~- [ ] error page~~ https://github.com/MutinyWallet/mutiny-web/issues/33

~~- [ ] Settings~~
	~~- [ ] seed info~~
	~~- [ ] backup wallet to json (temp, for dev purposes)~~
	~~- [ ] restore wallet from json (temp, for dev purposes)~~
	~~- [ ] edit service servers (network, blocks, lsp, ws proxy)~~
https://github.com/MutinyWallet/mutiny-web/issues/34

- [x] kitchen sink admin stuff
	- [x] list peers
	- [x] disconnect / delete peers
	- [x] list channels
	- [x] close channels

**Comment by TonyGiorgio** [comment]
I made seperate issues for all the remaining items above so we can more easily track these remaining efforts with all of the other tasks we have. Hope that's okay. They can be found in the "Next Milestone" area on our project board: https://github.com/orgs/MutinyWallet/projects/1/views/1
